version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: employees
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring_app:
    build: .
    container_name: employees_api_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql_data:
